# Generated by Django 3.0.3 on 2020-02-08 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
