# Generated by Django 3.0.3 on 2020-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0002_auto_20200208_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviereview',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
