# Generated by Django 3.0.3 on 2020-02-08 17:42

from django.db import migrations

def create_data(apps, shema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Movie(name='The Lord of the Rings: The Return of the King',
          description='Последняя часть трилогии о Кольце Всевластия и о героях, взявших на себя бремя спасения Средиземья. Повелитель сил Тьмы Саурон направляет свои бесчисленные рати под стены Минас-Тирита, крепости Последней Надежды. Он предвкушает близкую победу, но именно это и мешает ему заметить две крохотные фигурки — хоббитов, приближающихся к Роковой Горе, где им предстоит уничтожить Кольцо Всевластия. Улыбнется ли им счастье?',
          producer='Peter Jackson',
          duration=201,).save()
    Movie(name='Star Wars: Episode VI - Return of the Jedi',
          description='В шестом эпизоде «Звездных войн» Дарт Вейдер создает вторую «Звезду Смерти». Он объединяет все силы зла, чтобы с помощью этого смертоносного оружия нанести последний сокрушительный удар по повстанцам и их союзникам.',
          producer='Richard Marquand',
          duration=132).save()
    Movie(name='Blade Runner',
          description='Отставной детектив Рик Декард вновь восстановлен в полиции Лос-Анджелеса для поиска возглавляемой Роем Батти группы киборгов, совершившей побег из космической колонии на Землю.',
          producer='Ridley Scott',
          duration=117).save()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
