# Generated by Django 3.0.3 on 2020-02-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name']},
        ),
    ]
